#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit DLM (Distributed Lock Manager)
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

# This code is a program designed to manage locks and data storage in a system.
# It allows users to lock and unlock resources, as well as store, retrieve, and
# erase data associated with those resources. The program operates by listening
# for incoming requests on a specific port, processing these requests based on
# the actions specified (like locking or unlocking), and maintaining a record
# of active locks and their expiration times.

# When a user sends a request, the program checks if it’s valid and whether the
# requester has permission to perform the action. If everything checks out, it
# updates its records accordingly. The program also keeps track of various
# statistics related to its operations, such as how many requests it has
# handled or if there have been any errors.

# Additionally, it logs important events for monitoring purposes and manages
# memory efficiently by cleaning up expired locks or unused data. Overall, this
# code serves as an efficient tool for coordinating access to shared resources
# while ensuring that only authorized users can manipulate them.

# For (un)locking

# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Lock", "Expire":"300" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Unlock" }

# For memory reference

# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Get" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Put", "Expire":"300","DataStore":"Blah" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Erase" }

import sys
sys.path.append('/home/JackrabbitDLM')
import os
import gc
import time
from datetime import datetime
import socket
import select
import json

Version="0.0.0.1.500"
BaseDirectory="/home/JackrabbitDLM"
ConfigDirectory=f"{BaseDirectory}/Config"
LogDirectory=f"{BaseDirectory}/Logs"

# Statistics

Statistics={}

# Required global for the process to work

Locker={}

# Memory restrainst to optimize performance/stability. Reads this amount
# every call.

MaxBlockSize=4096

# Maximum TTL required to force authentication

MaxTTL=3543

# Maximum megabytes allowed for the entire payload. Prevents memory
# exhaustion (leaching) from malicious/bad program.

MaxPayloadSize=(10*1024*1024)

# This will determine when to force a full gc collect based upon the
# memory actually deleted.

MaxDataHoldSize=0

# Read authentication file from disk

def ReadAuthentication(fn):
    fname=f"{ConfigDirectory}/{fn}.cfg"
    if os.path.exists(fname):
        cf=open(fname,'r')
        buffer=cf.read().strip()
        cf.close()
        try:
            buffer=json.loads(buffer)
        except:
            buffer=None
        if buffer and 'Identity' in buffer and len(buffer['Identity'])<1023:
            buffer=None
    else:
        buffer=None
    return buffer

# Write pid in port file

def WritePID(port):
    fn=LogDirectory+'/'+str(port)+'.pid'
    f = open(fn, "w")
    f.write(str(os.getpid()))
    f.close()

# Write log entry

def WriteLog(msg):
    time=(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

    s=f'{time} {msg}\n'

    fh=open(LogDirectory+'/JackrabbitDLM.log','a')
    fh.write(s)
    fh.close()

# Convience to build the status and a json payload

def jsonStatus(str,id=None,Tag=None,Data=None):
    res={}
    res['Status']=str

    if id!=None:
        res['ID']=id

    if Tag!=None and Data!=None:
        res[Tag]=Data

    return json.dumps(res)+'\n'

# Check the authentication

def CheckAuthentication(dataDB,LockDB):
    # If name is in one or the other, fail.

    if ('Name' in dataDB and 'Name' not in LockDB) \
    or ('Name' not in dataDB and 'Name' in LockDB):
        return False

    # if name is in locker, test REQUIRED.

    if 'Name' in LockDB:
        if 'Name' not in dataDB \
        or 'Identity' not in dataDB \
        or 'Authenticator' not in dataDB \
        or dataDB['Name']!=LockDB['Name'] \
        or dataDB['Identity']!=LockDB['Identity']:
            return False

    # No authentication needed
    return True

# Process the payload and carry out each of the desired functionalities.

# Lock and DataStore MUST be different. Unlock REMOVES data as the same.

def ProcessPayload(data):
    global Statistics
    global Locker
    global MaxDataHoldSize

    try:
        dataDB=json.loads(data)
    except: # damaged payload
        Statistics['BadPayload']=Statistics.get('BadPayload',0)+1
        return jsonStatus("BadPayload")

    # Find the lock

    # FileName and Action are required. For memory fetches, FileName is memory ID.

    if 'FileName' not in dataDB \
    or 'Action' not in dataDB \
    or 'ID' not in dataDB \
    or 'Expire' not in dataDB:
        Statistics['BadPayload']=Statistics.get('BadPayload',0)+1
        return jsonStatus("BadPayload")

    # Verify any additional security layers.
    #
    # Checks:
    #   1. If "Name" is in the payload, then read the file (name.cfg)
    #   2. Verify "Identidy" and "Authenticator" string match. REQUIRED if
    #      "Name" is present.
    #   3. if "Expire" > 3543, force required authentiion
    #
    # If veryify fails, return only BadPayload... No authentication leaking.
    #
    # If you are crazy enough to use authentication for a lock/data that lasts
    # seconds to minutes, then these requirements are nothing to worry about.

    # Authentication REQUIRED for long term data storage.

    if float(dataDB['Expire'])>MaxTTL and 'Name' not in dataDB:
        Statistics['AuthFailed']=Statistics.get('AuthFailed',0)+1
        return jsonStatus("BadPayload")

    if 'Name' in dataDB:
        auth=ReadAuthentication(dataDB['Name'])

        # All the ways it can fail.
        if auth is None \
        or 'Identity' not in dataDB \
        or 'Authenticator' not in dataDB \
        or 'Identity' not in auth \
        or 'Authenticator' not in auth \
        or len(dataDB['Identity'])<1023 \
        or dataDB['Identity']!=auth['Identity']:
            Statistics['AuthFailed']=Statistics.get('AuthFailed',0)+1
            return jsonStatus("BadPayload")

    # Valid actions:
    #    Lock
    #    Unlock
    #    Get
    #    Put        Only this command allows a DataStore in the payload
    #    Erase

    # With what we are doing. FileName also doubles as memory ID
    FileName=dataDB['FileName']
    action=dataDB['Action'].lower()

    # Handle the LOCK action. This allows an advisory locking method
    # that should work on any platform. Locking/Unlocking can be
    # used as a rate limiter as well.

    if action=='lock':
        # New lock request
        if FileName not in Locker:
            dataLock={}
            dataLock['ID']=dataDB['ID']
            dataLock['Expire']=time.time()+float(dataDB['Expire'])
            Locker[FileName]=dataLock
            if 'Name' in dataDB:    # Add the authentication
                Locker[FileName]['Name']=dataDB['Name']
                Locker[FileName]['Identity']=dataDB['Identity']
            Statistics['Lock']=Statistics.get('Lock',0)+1
            return jsonStatus("Locked",Locker[FileName]['ID'])

        # Lock has expired, now unlocked
        if time.time()>Locker[FileName]['Expire']:
            Locker[FileName]['ID']=dataDB['ID'] # assign the new ID
            Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
            if 'Name' in dataDB:    # Add the authentication
                Locker[FileName]['Name']=dataDB['Name']
                Locker[FileName]['Identity']=dataDB['Identity']
            Statistics['Expired']=Statistics.get('Expired',0)+1
            Statistics['Lock']=Statistics.get('Lock',0)+1
            return jsonStatus("Locked",Locker[FileName]['ID'])

        # The current owner want the lock reset to a specific duration/held longer
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckAuthentication(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
            Statistics['Relock']=Statistics.get('Relock',0)+1
            return jsonStatus("Locked",Locker[FileName]['ID'])

        # Lock access by a non-owner ID
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    # Unlock request
    elif action=='unlock':
        # Just pass through unlock
        if FileName not in Locker:
            Statistics['UnlockNF']=Statistics.get('UnlockNF',0)+1
            return jsonStatus("Unlocked")

        # Verify owner and unlock
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckAuthentication(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            if Locker[FileName]['Expire']>0:
                Statistics['Unlock']=Statistics.get('Unlock',0)+1
            Locker[FileName]['Expire']=0
            return jsonStatus("Unlocked",Locker[FileName]['ID'])

        # Unock access by a non-owner ID. This may seem idiotic, but its an
        # absolute for keeping the lock from being hijacked.
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    # Get memory reference
    elif action=='get':
        # Memory item doesn't exist
        if FileName not in Locker:
            Statistics['GetNF']=Statistics.get('GetNF',0)+1
            return jsonStatus("NotFound")

        # Verify owner of data
        if Locker[FileName]['ID']==dataDB['ID'] and time.time()<=Locker[FileName]['Expire']:
            if not CheckAuthentication(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            if 'DataStore' in Locker[FileName]:
                Statistics['Get']=Statistics.get('Get',0)+1
                Statistics['DataOut']=Statistics.get('DataOut',0)+len(Locker[FileName]['DataStore'])
                return jsonStatus("Done",Locker[FileName]['ID'],Tag="DataStore",Data=Locker[FileName]['DataStore'])

            Statistics['GetNF']=Statistics.get('GetNF',0)+1
            return jsonStatus("NoData",Locker[FileName]['ID'])

        # Not the rightful owner
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    elif action=='put':
        # If there is no DataStore, its broke.
        if 'DataStore' not in dataDB:
            Statistics['BadPayload']=Statistics.get('BadPayload',0)+1
            return jsonStatus("BadPayload")

        # New memory object
        if FileName not in Locker:
            dStore={}
            dStore['ID']=dataDB['ID']
            dStore['Expire']=time.time()+float(dataDB['Expire'])
            dStore['DataStore']=dataDB['DataStore']
            Locker[FileName]=dStore
            if 'Name' in dataDB:    # Add the authentication
                Locker[FileName]['Name']=dataDB['Name']
                Locker[FileName]['Identity']=dataDB['Identity']
            Statistics['PutNew']=Statistics.get('PutNew',0)+1
            Statistics['DataIn']=Statistics.get('DataIn',0)+len(dataDB['DataStore'])
            return jsonStatus("Done",Locker[FileName]['ID'])

        # Existing memory object, verify owner and reset expiration timeout
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckAuthentication(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
            Locker[FileName]['DataStore']=dataDB['DataStore']
            Statistics['DataIn']=Statistics.get('DataIn',0)+len(dataDB['DataStore'])
            Statistics['PutUpdate']=Statistics.get('PutUpdate',0)+1
            return jsonStatus("Done",Locker[FileName]['ID'])

        # Not the rightful owner
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    # Erase request
    elif action=='erase':
        # Just pass through erase
        if FileName not in Locker:
            Statistics['EraseNF']=Statistics.get('EraseNF',0)+1
            return jsonStatus("NotFound")

        # if NO DataStore, corrupted memory item...
        if 'DataStore' not in Locker[FileName]:
            Locker[FileName]['Expire']=0
            Statistics['Corruption']=Statistics.get('Corruption',0)+1
            return jsonStatus("Corruption")

        # Verify owner and erase memory. Erase is just resetting expiration to 0.
        # Will be remove in main function.
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckAuthentication(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            Locker[FileName]['Expire']=0
            MaxDataHoldSize+=len(Locker[FileName]['DataStore'])
            Locker[FileName]['DataStore']=None
            Statistics['Erased']=Statistics.get('Erased',0)+1
            return jsonStatus("Done",Locker[FileName]['ID'])

        # Not the rightful owner, fall thru
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")

    # get active version number
    elif action=='version':
        return jsonStatus("Version",f"JackrabbitDLM/{Version}")

    # Wrong key
    Statistics['BadAction']=Statistics.get('BadAction',0)+1
    return jsonStatus("BadAction")

###
### Main Driver
###

def main():
    global Statistics
    global Locker
    global MaxDataHoldSize

    OldHour=-1

    WriteLog(f"Jackrabbit DLM {Version}")

    host=''
    port=37373

    if len(sys.argv)>1:
        host=sys.argv[1]
    if len(sys.argv)>2:
        port=int(sys.argv[2])

    # Data storage for incoming payloads
    dataStore={}

    WritePID(port)

    # Open the port.

    try:
        lockerSocket=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        lockerSocket.setblocking(0)
        lockerSocket.bind((host, port))
        lockerSocket.listen(1024)
    except OSError as err:
        x=str(err)
        if x.find('Address already in use')>-1:
            x='Another program is using this port: '+str(port)
        WriteLog(x)
        sys.exit(1)

    # Track incoming connections

    inputs=[lockerSocket]

    # Response queue connected to each client

    queue={}

    # The main loop of the program.

    while True:
        infds,outfds,errfds=select.select(inputs, inputs, [], 30)

        if len(infds)!=0:
            Statistics['AIn']=len(infds)
            for fds in infds:
                # Inbound requests processed
                Statistics['In']=Statistics.get('In',0)+1
                if fds is lockerSocket:
                    # Get new connection
                    clientsock,clientaddr=fds.accept()
                    clientsock.setblocking(0)
                    if clientsock not in inputs:
                        inputs.append(clientsock)
                    dataStore[clientsock]=''
                else:
                    data=None
                    try:
                        data=fds.recv(MaxBlockSize)
                    except:
                        # Memory management when timeout
                        gc.collect()
                        # Sleep based upon server load
                        Statistics['Idle']=Statistics.get('Idle',0)+1
                        time.sleep(1)

                    # No data received, close connection, clean up and sleep

                    if not data or data==None:
                        if fds in dataStore:
                            MaxDataHoldSize+=len(dataStore[fds])
                            dataStore.pop(fds,None)
                        if fds in inputs:
                            inputs.remove(fds)
                        if fds in queue:
                            queue.pop(fds,None)
                        fds.close()
                    else:
                        # Sanity check to prevent memory exhaustion
                        # Potential attack
                        if len(dataStore[fds])+len(data)>MaxPayloadSize:
                            if fds in dataStore:
                                MaxDataHoldSize+=len(dataStore[fds])
                                dataStore.pop(fds,None)
                            if fds in inputs:
                                inputs.remove(fds)
                            if fds in queue:
                                queue.pop(fds,None)
                            fds.close()
                            Statistics['DataOverrun']=Statistics.get('DataOverrun',0)+1
                            continue

                        # Collect the entire line.
                        try:
                            data=data.decode('utf-8')
                        except:
                            continue
                        dataStore[fds]+=data
                        # One and ONLY one request allowed
                        if dataStore[fds][-1]=='\n':
                            queue[fds]=ProcessPayload(dataStore[fds])

        # Send response and close connection

        if len(outfds)!=0:
            Statistics['AOut']=len(outfds)
            for fds in outfds:
                # Outbound requests processed
                Statistics['Out']=Statistics.get('Out',0)+1
                if fds in queue:
                    try:
                        fds.setblocking(1)
                        fds.sendall(queue[fds].encode())
                    except:
                        if fds in dataStore:
                            MaxDataHoldSize+=len(dataStore[fds])
                            dataStore.pop(fds,None)
                        if fds in inputs:
                            inputs.remove(fds)
                        fds.close()
                    queue.pop(fds,None)

        # Clean up memory list

        # Active Locks/Data
        Statistics['ALock']=0
        Statistics['AData']=0

        now=time.time()
        for k in list(Locker):
            if now>Locker[k]['Expire']:
                if 'DataStore' in Locker[k]:
                    if Locker[k]['DataStore'] is not None:
                        MaxDataHoldSize+=len(Locker[k]['DataStore'])
                        Locker[k]['DataStore']=None
                    Statistics['ExpiredData']=Statistics.get('ExpiredData',0)+1
                else:
                    Statistics['ExpiredLock']=Statistics.get('ExpiredLock',0)+1
                Locker.pop(k,None)
            # For accuracy, must be after possible removal, Active
            if k in Locker:
                if 'DataStore' in Locker[k]:
                    Statistics['AData']+=1
                else:
                    Statistics['ALock']+=1

        ct=datetime.now()
        if ct.hour!=OldHour and len(Statistics)>0:
            OldHour=ct.hour

            s=', '.join(f"{k}: {v}" for k,v in sorted(Statistics.items()) if v>0)
            WriteLog(s)
            Statistics={}

        # Long term memory management
        if MaxDataHoldSize>MaxPayloadSize:
            Statistics['ForcedGC']=Statistics.get('ForcedGC',0)+1
            MaxDataHoldSize=0
            gc.collect()

if __name__ == '__main__':
    main()
