#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit DLM (Distributed Lock Manager)
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

# This code is a program designed to manage locks and data storage in a system.
# It allows users to lock and unlock resources, as well as store, retrieve, and
# erase data associated with those resources. The program operates by listening
# for incoming requests on a specific port, processing these requests based on
# the actions specified (like locking or unlocking), and maintaining a record
# of active locks and their expiration times.

# REQUIRED AT ALL TIMES (see client library dor details:
#   ID, FileName, Action, Expire

# For (un)locking

# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Lock", "Expire":"300" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Unlock" }

# For memory reference

# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Get" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Put", "Expire":"300","DataStore":"Blah" }
# { "ID":"DEADBWEEF", "FileName":"testData", "Action":"Erase" }

import sys
sys.path.append('/home/JackrabbitDLM')
import os
import gc
import time
from datetime import datetime
import socket
import select
import json

Version="0.0.0.2.0"
BaseDirectory="/home/JackrabbitDLM"
ConfigDirectory=f"{BaseDirectory}/Config"
LogDirectory=f"{BaseDirectory}/Logs"

# Statistics

Statistics={}

# Required global for the process to work

Locker={}

# Memory restrainst to optimize performance/stability. Reads this amount
# every call.

MaxBlockSize=4096

# Maximum TTL required to force authentication. This will also be the threshold
# for future persistent storage.

MaxTTL=3543

# Maximum megabytes allowed for the entire payload. Prevents memory exhaustion
# (leaching) from malicious/bad program. FUTURE CONSIDERATIONS: Limits differ
# per authenticated entries.

MaxPayloadSize=(1*1024*1024)

# This will determine when to force a full gc collect based upon the
# memory actually deleted.

MaxDataHoldSize=0

# Read authentication file from disk

def ReadIdentity(fn):
    fname=f"{ConfigDirectory}/{fn}.cfg"
    if os.path.exists(fname):
        cf=open(fname,'r')
        buffer=cf.read().strip()
        cf.close()
        try:
            buffer=json.loads(buffer)
        except:
            buffer=None
        if buffer and 'Identity' in buffer and len(buffer['Identity'])<1023:
            buffer=None
    else:
        buffer=None
    return buffer

# Write pid in port file

def WritePID(port):
    fn=LogDirectory+'/'+str(port)+'.pid'
    f=open(fn, "w")
    f.write(str(os.getpid()))
    f.close()

# Write log entry

def WriteLog(msg):
    time=(datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f'))

    s=f'{time} {msg}\n'

    fh=open(LogDirectory+'/JackrabbitDLM.log','a')
    fh.write(s)
    fh.close()

# Convience to build the status and a json payload

def jsonStatus(str,id=None,Tag=None,Data=None):
    res={}
    res['Status']=str

    if id!=None:
        res['ID']=id

    if Tag!=None and Data!=None:
        res[Tag]=Data

    return json.dumps(res)+'\n'

# Is it a number?

def NumberOnly(s):
    try:
        x=float(s)
        return True
    except:
        return False
    return False

# Check the authentication

def CheckIdentity(dataDB,LockDB):
    # If name is in one or the other, fail.

    if ('Name' in dataDB and 'Name' not in LockDB) \
    or ('Name' not in dataDB and 'Name' in LockDB):
        return False

    # if name is in locker, test REQUIRED.

    if 'Name' in LockDB:
        if 'Name' not in dataDB \
        or 'Identity' not in dataDB \
        or dataDB['Name']!=LockDB['Name'] \
        or dataDB['Identity']!=LockDB['Identity']:
            return False

    # No authentication needed
    return True

# Process the payload and carry out each of the desired functionalities.

# Lock and DataStore MUST be different. Unlock REMOVES data as the same.

def ProcessPayload(data):
    global Statistics
    global Locker
    global MaxDataHoldSize

    try:
        dataDB=json.loads(data)
    except: # damaged payload
        Statistics['BadPayload']=Statistics.get('BadPayload',0)+1
        return jsonStatus("BadPayload")

    # Find the lock

    # FileName and Action are required. For memory fetches, FileName is memory ID.

    if 'FileName' not in dataDB \
    or 'Action' not in dataDB \
    or 'ID' not in dataDB \
    or 'Expire' not in dataDB \
    or not NumberOnly(dataDB['Expire']):
        Statistics['BadPayload']=Statistics.get('BadPayload',0)+1
        return jsonStatus("BadPayload")

    # Verify any additional security layers.
    #
    # Checks:
    #   1. If "Name" is in the payload, then read the file (name.cfg)
    #   2. Verify "Identidy" string match. REQUIRED if
    #      "Name" is present.
    #   3. if "Expire" > 3543, force required authentiion
    #
    # If veryify fails, return only BadPayload... No authentication leaking.
    #
    # If you are crazy enough to use authentication for a lock/data that lasts
    # seconds to minutes, then these requirements are nothing to worry about.

    # Authentication REQUIRED for long term data storage.

    if float(dataDB['Expire'])>MaxTTL and 'Name' not in dataDB:
        Statistics['AuthFailed']=Statistics.get('AuthFailed',0)+1
        return jsonStatus("BadPayload")

    if 'Name' in dataDB:
        auth=ReadIdentity(dataDB['Name'])

        # All the ways it can fail.
        if auth is None \
        or 'Identity' not in dataDB \
        or 'Identity' not in auth \
        or len(dataDB['Identity'])<1023 \
        or dataDB['Identity']!=auth['Identity']:
            Statistics['AuthFailed']=Statistics.get('AuthFailed',0)+1
            return jsonStatus("BadPayload")

    # Valid actions:
    #   Lock
    #   Unlock
    #   Get
    #   Put
    #   Erase
    #   Version

    # With what we are doing. FileName also doubles as memory ID
    FileName=dataDB['FileName']
    action=dataDB['Action'].lower()

    # Handle the LOCK action. This allows an advisory locking method
    # that should work on any platform. Locking/Unlocking can be
    # used as a rate limiter as well.

    if action=='lock':
        # New lock request
        if FileName not in Locker \
        or time.time()>Locker[FileName]['Expire']:
            dataLock={}
            dataLock['ID']=dataDB['ID']
            dataLock['Expire']=time.time()+float(dataDB['Expire'])
            Locker[FileName]=dataLock
            if 'Name' in dataDB:    # Add the authentication
                Locker[FileName]['Name']=dataDB['Name']
                Locker[FileName]['Identity']=dataDB['Identity']
            Statistics['Lock']=Statistics.get('Lock',0)+1
            return jsonStatus("Locked",Locker[FileName]['ID'])

        # The current owner want the lock reset to a specific duration/held longer
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckIdentity(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
            Statistics['Relock']=Statistics.get('Relock',0)+1
            return jsonStatus("Locked",Locker[FileName]['ID'])

        # Lock access by a non-owner ID
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    # Unlock request
    elif action=='unlock':
        # Just pass through unlock
        if FileName not in Locker:
            Statistics['UnlockNF']=Statistics.get('UnlockNF',0)+1
            return jsonStatus("Unlocked")

        # Verify owner and unlock
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckIdentity(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            if Locker[FileName]['Expire']>0:
                Statistics['Unlock']=Statistics.get('Unlock',0)+1
            Locker[FileName]['Expire']=0
            return jsonStatus("Unlocked",Locker[FileName]['ID'])

        # Unock access by a non-owner ID. This may seem idiotic, but its an
        # absolute for keeping the lock from being hijacked.
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    # Get memory reference
    elif action=='get':
        # Memory item doesn't exist
        if FileName not in Locker:
            Statistics['GetNF']=Statistics.get('GetNF',0)+1
            return jsonStatus("NotFound")

        # Verify owner of data
        if Locker[FileName]['ID']==dataDB['ID'] and time.time()<=Locker[FileName]['Expire']:
            if not CheckIdentity(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            if 'DataStore' in Locker[FileName]:
                Statistics['Get']=Statistics.get('Get',0)+1
                Statistics['DataOut']=Statistics.get('DataOut',0)+len(Locker[FileName]['DataStore'])
                return jsonStatus("Done",Locker[FileName]['ID'],Tag="DataStore",Data=Locker[FileName]['DataStore'])

            Statistics['GetNF']=Statistics.get('GetNF',0)+1
            return jsonStatus("NoData",Locker[FileName]['ID'])

        # Not the rightful owner
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    elif action=='put':
        # If there is no DataStore, its broke.
        if 'DataStore' not in dataDB:
            Statistics['BadPayload']=Statistics.get('BadPayload',0)+1
            return jsonStatus("BadPayload")

        # New memory object
        if FileName not in Locker \
        or time.time()>Locker[FileName]['Expire']:
            dStore={}
            dStore['ID']=dataDB['ID']
            dStore['Expire']=time.time()+float(dataDB['Expire'])
            dStore['DataStore']=dataDB['DataStore']
            Locker[FileName]=dStore
            if 'Name' in dataDB:    # Add the authentication
                Locker[FileName]['Name']=dataDB['Name']
                Locker[FileName]['Identity']=dataDB['Identity']
            Statistics['PutNew']=Statistics.get('PutNew',0)+1
            Statistics['DataIn']=Statistics.get('DataIn',0)+len(dataDB['DataStore'])
            return jsonStatus("Done",Locker[FileName]['ID'])

        # Existing memory object, verify owner and reset expiration timeout
        # Data is strange case. it is either erared or expired by main loop.
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckIdentity(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            Locker[FileName]['Expire']=time.time()+float(dataDB['Expire'])
            Locker[FileName]['DataStore']=dataDB['DataStore']
            Statistics['DataIn']=Statistics.get('DataIn',0)+len(dataDB['DataStore'])
            Statistics['PutUpdate']=Statistics.get('PutUpdate',0)+1
            return jsonStatus("Done",Locker[FileName]['ID'])

        # Not the rightful owner
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")
    # Erase request
    elif action=='erase':
        # Just pass through erase
        if FileName not in Locker:
            Statistics['EraseNF']=Statistics.get('EraseNF',0)+1
            return jsonStatus("NotFound")

        # if NO DataStore, corrupted memory item...
        if 'DataStore' not in Locker[FileName]:
            Locker[FileName]['Expire']=0
            Statistics['Corruption']=Statistics.get('Corruption',0)+1
            return jsonStatus("Corruption")

        # Verify owner and erase memory. Erase is just resetting expiration to 0.
        # Will be remove in main function.
        if Locker[FileName]['ID']==dataDB['ID']:
            if not CheckIdentity(dataDB,Locker[FileName]):
                # Lock access by a non-owner ID
                Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
                return jsonStatus("NotOwner")

            Locker[FileName]['Expire']=0
            MaxDataHoldSize+=len(Locker[FileName]['DataStore'])
            Locker[FileName]['DataStore']=None
            Statistics['Erased']=Statistics.get('Erased',0)+1
            return jsonStatus("Done",Locker[FileName]['ID'])

        # Not the rightful owner, fall thru
        Statistics['NotOwner']=Statistics.get('NotOwner',0)+1
        return jsonStatus("NotOwner")

    # get active version number
    elif action=='version':
        return jsonStatus("Version",f"JackrabbitDLM/{Version}")

    # Wrong key
    Statistics['BadAction']=Statistics.get('BadAction',0)+1
    return jsonStatus("BadAction")

###
### Main Driver
###

def main():
    global Statistics
    global Locker
    global MaxDataHoldSize

    OldHour=-1

    WriteLog(f"Jackrabbit DLM {Version}")

    host=''
    port=37373

    if len(sys.argv) > 1:
        host=sys.argv[1]
    if len(sys.argv) > 2:
        port=int(sys.argv[2])

    dataStore={}
    queue={}
    sendBuffer={}

    try:
        lockerSocket=socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        lockerSocket.setblocking(0)
        lockerSocket.bind((host, port))
        lockerSocket.listen(1024)
    except OSError as err:
        x=str(err)
        if 'Address already in use' in x:
            x='Another program is using this port: '+str(port)
        WriteLog(x)
        sys.exit(1)

    WritePID(port)

    poller=select.poll()
    fdmap={}

    poller.register(lockerSocket, select.POLLIN)
    fdmap[lockerSocket.fileno()]=lockerSocket

    while True:
        # 30 decond timeout for IDLE
        events=poller.poll(30000)

        if not events:
            # Idle phase
            Statistics['Idle']=Statistics.get('Idle', 0)+1
            if MaxDataHoldSize > MaxPayloadSize:
                # Force GC to clean
                Statistics['ForcedGC']=Statistics.get('ForcedGC', 0)+1
                MaxDataHoldSize=0
                gc.collect()

        # Track active in/out
        actin=0
        actout=0

        # Event loop
        for fd, event in events:
            fds=fdmap.get(fd)
            if fds is None:
                continue

            # New connection
            if fds is lockerSocket:
                try:
                    clientsock, clientaddr=fds.accept()
                    clientsock.setblocking(0)

                    poller.register(clientsock, select.POLLIN)
                    fdmap[clientsock.fileno()]=clientsock

                    dataStore[clientsock]=''
                    Statistics['Connections']=Statistics.get('Connections', 0)+1
                except:
                    continue

            # Read event
            elif event & select.POLLIN:
                actin+=1
                data=None
                try:
                    data=fds.recv(MaxBlockSize)
                except:
                    pass

                if not data:
                    if fds in dataStore:
                        MaxDataHoldSize += len(dataStore[fds])
                        dataStore.pop(fds, None)

                    if fds in queue:
                        queue.pop(fds, None)

                    if fds in sendBuffer:
                        sendBuffer.pop(fds, None)

                    poller.unregister(fds)
                    fdmap.pop(fd, None)
                    fds.close()
                    continue

                if len(dataStore[fds])+len(data) > MaxPayloadSize:
                    MaxDataHoldSize += len(dataStore.get(fds, ''))
                    dataStore.pop(fds, None)
                    queue.pop(fds, None)
                    sendBuffer.pop(fds, None)

                    poller.unregister(fds)
                    fdmap.pop(fd, None)
                    fds.close()

                    Statistics['DataOverrun']=Statistics.get('DataOverrun', 0)+1
                    continue

                # I don't want bad connections tracked
                Statistics['In']=Statistics.get('In', 0)+1

                try:
                    data=data.decode('utf-8')
                except:
                    continue

                dataStore[fds] += data

                if dataStore[fds] and dataStore[fds].endswith('\n'):
                    response=ProcessPayload(dataStore[fds])
                    sendBuffer[fds]=response.encode('utf-8')
                    poller.modify(fds, select.POLLOUT)

            # Write event using send()
            elif event & select.POLLOUT:
                actout+=1
                if fds in sendBuffer:
                    try:
                        sent=fds.send(sendBuffer[fds])
                    except:
                        sent=0

                    if sent > 0:
                        sendBuffer[fds]=sendBuffer[fds][sent:]

                    # If all data sent, close connection (same behavior as original)
                    if not sendBuffer[fds]:
                        sendBuffer.pop(fds, None)

                        if fds in dataStore:
                            MaxDataHoldSize += len(dataStore[fds])
                            dataStore.pop(fds, None)

                        poller.unregister(fds)
                        fdmap.pop(fd, None)
                        fds.close()

                        Statistics['Out']=Statistics.get('Out', 0)+1

            # Error / hangup
            elif event & (select.POLLHUP | select.POLLERR):
                Statistics['BadConn']=Statistics.get('BadConn', 0)+1
                if fds in dataStore:
                    MaxDataHoldSize += len(dataStore[fds])
                    dataStore.pop(fds, None)

                if fds in queue:
                    queue.pop(fds, None)

                if fds in sendBuffer:
                    sendBuffer.pop(fds, None)

                poller.unregister(fds)
                fdmap.pop(fd, None)
                fds.close()

        # Active in/out events
        Statistics['AIn']=actin
        Statistics['AOut']=actout

        # Cleanup expired locks/data and track only active locks/data
        Statistics['ALock']=0
        Statistics['AData']=0

        # Purge expired
        now=time.time()
        for k in list(Locker):
            if now > Locker[k]['Expire']:
                if 'DataStore' in Locker[k]:
                    if Locker[k]['DataStore'] is not None:
                        MaxDataHoldSize += len(Locker[k]['DataStore'])
                        Locker[k]['DataStore']=None
                    Statistics['ExpiredData']=Statistics.get('ExpiredData', 0)+1
                else:
                    Statistics['ExpiredLock']=Statistics.get('ExpiredLock', 0)+1
                Locker.pop(k, None)

            # Count the active enty only
            if k in Locker:
                if 'DataStore' in Locker[k]:
                    Statistics['AData'] += 1
                else:
                    Statistics['ALock'] += 1

        # Log the statistics
        ct=datetime.now()
        if ct.hour != OldHour and len(Statistics)>0:
            OldHour=ct.hour
            s=', '.join(f"{k}: {v}" for k,v in sorted(Statistics.items()) if v>0)
            WriteLog(s)
            Statistics={}

        # Check for a foced GC run. Keep the system as lean as possible.
        if MaxDataHoldSize>MaxPayloadSize:
            # Force GC to clean
            Statistics['ForcedGC']=Statistics.get('ForcedGC', 0)+1
            MaxDataHoldSize=0
            gc.collect()

###
### Main driver
###

if __name__ == '__main__':
    main()
