#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# Jackrabbit DLM
# 2021 Copyright © Robert APM Darin
# All rights reserved unconditionally.

import sys
sys.path.append('/home/GitHub/JackrabbitDLM')
import os
import time
import json
import random

import DLMLocker as DLM

m=1000
if len(sys.argv)>1:
    m=int(sys.argv[1])

RetryLocker=True
if len(sys.argv)>2:
    RetryLocker=False

c=0     # Memory counter
f=0     # Failed locks
s=0     # Successful locks
r=0     # Reads
w=0     # Writes

# Connection timeout is 10 seconds
fw1=DLM.Locker("LockerTest",Timeout=10,Retry=0)
Memory=DLM.Locker('LockFighter',ID='LockFighterMemory')

if not fw1.IsDLM():
    print("JackrabbitDLM not found/running")
    sys.exit(1)

# Every fight gets a different write value frequency. Goal is chaos.
wv=random.random()
stime=time.time()
while c<m:
    rl=None
    if RetryLocker:
        rl=fw1.Lock(expire=10)       # Retry framework
    else:
        rl=fw1.IsLocked(expire=10)   # Hyper aggressive, no retry

    if rl=='locked':
        try:
            Junker=DLM.Locker('Junker')
            # Consume
            sData=Memory.Get()
            r+=1
            # If found, increment
            if 'DataStore' in sData:
                c=int(sData['DataStore'])

                # Write (produce) 25% of the time
                rn=random.random()
                if c<m and rn>round(wv,2):
                    c+=1
                    Memory.Put(data=str(c),expire=10)
                    w+=1
                # Make a random block of garbage that will be abandoned
                if rn>0.5:
                    Junker.Put(data=str(os.urandom(128*1024)),expire=5)
                rn=random.random()
                # Play nice and clean up.
                if rn>0.75:
                    Junker.Erase()
            # If not found, create it
            else:
                Memory.Put(data=str(c),expire=10)
                w+=1
            s+=1
        except Exception as err:
            f+=1
            print(err)
            if RetryLocker:
                time.sleep(0.1)
        fw1.Unlock()
    else:
        f+=1
        if RetryLocker:
            time.sleep(0.1)

# A proper program would use some kind of a waiting period to play nice with the CPU.
#    time.sleep(0.1)

etime=time.time()
# contention rate
cr=0
if f>0:
    cr=round((f/(s+f))*100,2)
print(str(RetryLocker)[0],os.getpid(),f"{etime-stime:.8f}",f,s,r,w,cr,c)
